version: '3'
services:
  static_server:
    container_name: static_server
    image: halverneus/static-file-server
    expose:
      - "8101"
    ports:
      - "8101:8080"
    environment:
      cors: false
      debug: false
    volumes:
      - videos:/web
  vlcache:
    container_name: vlcache_cont
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8100:8100"
    networks:
      - db_net
      - service_net
    depends_on:
      - main_db
      - kafka1
    volumes:
      - videos:/videos
  main_db:
    image: postgres
    container_name: postgres_main
    shm_size: 128mb
    environment:
      POSTGRES_USER: dvpsqluser
      POSTGRES_PASSWORD: dvpsql
      POSTGRES_DB: db_data
    expose:
      - "5440"
    ports:
      - "5440:5440"
    command: -p 5440
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /private/var/lib/db_cdr:/var/lib/postgresql
      - db:/data/postgres
    restart: unless-stopped
    networks:
      - db_net
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - kafka_net
  kafka1:
    container_name: kafka_bro_1
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9092"
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "data-topic:2:1"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - service_net
      - kafka_net
  kafka2:
    container_name: kafka_bro_2
    image: wurstmeister/kafka:latest
    ports:
      - "9094:9094"
    expose:
      - "9094"
      - "9095"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9095,OUTSIDE://kafka2:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "data-topic:2:1, video-topic:2:1"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - service_net
      - kafka_net
volumes:
  db:
  videos:
networks:
  db_net:
    driver: bridge
  db_net_admin:
    driver: bridge
  kafka_net:
    driver: bridge
  service_net:
    driver: bridge